# Generated by Django 3.2 on 2021-04-13 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ribapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractor',
            name='user',
        ),
    ]
